swagger: '2.0'
info: {description: Belfast based driving school specializing in providing high quality
    affordable driving lessons. We offer highly competetive prices from a DOE approved
    driving instructor., title: ET Driving School, version: 0.0.1}
schemes: [https]
basePath: /prod
host: g5lns65xdc.execute-api.eu-west-1.amazonaws.com
paths:
  /contact:
    post:
      consumes: [application/json]
      description: Sends inserted contact form details via email to ET Driving School
        admin
      parameters:
        - description: Contact form details
          in: body
          name: Contact
          required: true
          schema: {$ref: '#/definitions/Contact'}
      produces: [application/json]
      responses:
        201: {description: Contact email sent successfully}
      x-amazon-apigateway-integration:
        contentHandling: CONVERT_TO_TEXT
        httpMethod: POST
        passthroughBehavior: when_no_match
        responses:
          default: {statusCode: '200'}
        type: aws_proxy
        uri: arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:326341022855:function:etdrivingschool-contact/invocations
  /tweet:
    get:
      description: Returns recent tweets of etdrivingschool twitter user
      produces: [application/json]
      responses:
        200: {description: Tweets successfully returned}
      x-amazon-apigateway-integration:
        contentHandling: CONVERT_TO_TEXT
        httpMethod: POST
        passthroughBehavior: when_no_match
        responses:
          default: {statusCode: '200'}
        type: aws_proxy
        uri: arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:326341022855:function:etdrivingschool-tweet/invocations
definitions:
  Contact:
    properties:
      email: {format: email, type: string}
      message: {type: string}
      title: {type: string}
    type: object
